config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.xml { render xml: @kittens }
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render xml: @kitten }
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = "Successfully created a new kitten"
      redirect_to @kitten_path
    else
      flash.now[:error] = "UPS!, There errors in your request"
      render :new, :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(paramas[:id])

    if @kitten.update(kitten_params)
      flash[:success] = "Successfully updated kitten"
      redirect_to @kitten_path
    else
      flash.now[:error] = "UPS!, There errors in your request"
      render :new, :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    flash[:success] = "Successfully deleted kitten"
    redirect_to root_path, status: :see_other
  end

  private

  def kitten_params
    paramas.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form|%>
<% @kitten.errors.full_messages.each do |error|%>
  <div>
    <%= error%>
  </div>
<% end %>

  <div>
    <%= form.label :name%>
    <%= form.text_field :name %>
  </div>

<div>
    <%= form.label :age%>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness%>
    <%= form.number_field :cuteness %>
  </div>

  <div>
    <%= form.label :softness%>
    <%= form.number_field :softness %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1> Edit Kitten </h1>

<%= render "form", kitten: @kitten %>

<%= link_to "List all", kittens_path %>

app/views/kittens/index.html.erb
<h1>List of kittens</h1>

<%= link_to "Create new kitten", new_kitten_path %>

<% @kittens.each do |kitten|%>
  <div>
    <h1>Name: <%= kitten.name %></h1>
    <p>Age: <%= kitten.age %></p>
    <p>Cuteness: <%= kitten.cuteness %></p>
    <p>Softness: <%= kitten.softness %></p>
    <%= link_to "Show", kitten_path(kitten) %>
    <%= link_to "Edit", edit_kitten_path(kitten) %>
    <%= link_to "Delete", kitten_path(kitten), data: {
        turbo_method: :delete} %>
  </div>

<%end%>

app/views/kittens/new.html.erb
<h1> Crear Kitten </h1>

<%= render "form", kitten: @kitten %>

<%= link_to "List all", kittens_path %>

app/views/kittens/show.html.erb
<h1>Show kitten</h1>

<div>
  <h1>Name: <%= @kitten.name %></h1>
  <p>Age: <%= @kitten.age %></p>
  <p>Cuteness: <%= @kitten.cuteness %></p>
  <p>Softness: <%= @kitten.softness %></p>
    <%= link_to "List all", kittens_path %>
    <%= link_to "Edit", edit_kitten_path(@kitten) %>
    <%= link_to "Delete", kitten_path(@kitten), data: {
        turbo_method: :delete} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdingKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>